services:
  app:
    build: .
    container_name: file-drive
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Djavax.net.ssl.trustStore=/certs/truststore.p12
        -Djavax.net.ssl.trustStorePassword=changeit
        -Djavax.net.ssl.trustStoreType=PKCS12

      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/mydb;AUTO_SERVER=TRUE

      S3_ENDPOINT: https://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      S3_BUCKET: file-drive-bucket

    volumes:
      - ./data:/app/data
      - ./certs/app/truststore.p12:/certs/truststore.p12:ro

    depends_on:
      - minio
      - minio-init

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    volumes:
      - ./minio-data:/data
      - ./certs/minio/public.crt:/root/.minio/certs/public.crt:ro
      - ./certs/minio/private.key:/root/.minio/certs/private.key:ro

  # Create the bucket once MinIO is up
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      until mc alias set local https://minio:9000 minioadmin minioadmin123 --insecure; do
        sleep 2;
      done;
      mc mb -p local/file-drive-bucket --insecure || true;
      mc anonymous set download local/file-drive-bucket --insecure || true;
      echo 'Bucket is ready';
      "