services:
  app:
    build: .
    container_name: file-drive
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310
      JAVA_TOOL_OPTIONS: >-
        -Djavax.net.ssl.trustStore=/certs/truststore.p12
        -Djavax.net.ssl.trustStorePassword=changeit
        -Djavax.net.ssl.trustStoreType=PKCS12
        

      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/mydb;AUTO_SERVER=TRUE

      S3_ENDPOINT: https://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      S3_BUCKET: file-drive-bucket
      S3_QUARANTINE_BUCKET: file-drive-quarantine

    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
      - ./certs/app/truststore.p12:/certs/truststore.p12:ro
      - ./certs/app/server-keystore.p12:/certs/app/server-keystore.p12:ro

    depends_on:
      - minio
      - minio-init
      - clamav
  frontend:
    build: ./frontend
    container_name: file-drive-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app


  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    depends_on:
      - kes
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123

      MINIO_KMS_KES_ENDPOINT: https://kes:7373
      MINIO_KMS_KES_API_KEY: ${MINIO_KMS_KES_API_KEY}
      MINIO_KMS_KES_CAPATH: /certs/rootCA.crt
      MINIO_KMS_KES_KEY_NAME: file-drive-master-key
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    volumes:
      - ./minio-data:/data
      - ./certs/minio/public.crt:/root/.minio/certs/public.crt:ro
      - ./certs/minio/private.key:/root/.minio/certs/private.key:ro
      - ./certs/rootCA.crt:/certs/rootCA.crt:ro

  kes:
    image: minio/kes:latest
    container_name: kes
    command: server --config /config/server-config.yml
    ports:
      - "7373:7373"
    volumes:
      - ./kes/server-config.yml:/config/server-config.yml:ro
      - ./certs/kes/public.crt:/certs/public.crt:ro
      - ./certs/kes/private.key:/certs/private.key:ro
      - ./kes-data:/kes-data

  clamav:
    image: clamav/clamav:stable
    container_name: clamav
    restart: unless-stopped
    expose:
      - "3310"
    environment:
      CLAMD_CONF_StreamMaxLength: 500M
      CLAMD_CONF_MaxFileSize: 500M
      CLAMD_CONF_MaxScanSize: 500M
    volumes:
      - ./clamav-db:/var/lib/clamav

  # Create the bucket once MinIO is up
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      until mc alias set local https://minio:9000 minioadmin minioadmin123 --insecure; do
        sleep 2;
      done;
      mc mb -p local/file-drive-bucket --insecure || true;
      mc admin kms key create local file-drive-master-key --insecure || true;
      mc encrypt set sse-s3 local/file-drive-bucket --insecure || true;
      mc encrypt info local/file-drive-bucket --insecure || true;
      mc anonymous set download local/file-drive-bucket --insecure || true;
      mc mb -p local/file-drive-quarantine --insecure || true;
      mc anonymous set none local/file-drive-quarantine --insecure || true;
      
      mc mb -p local/file-drive-trash --insecure || true;
      mc encrypt set sse-s3 local/file-drive-trash --insecure || true;
      mc encrypt info local/file-drive-trash --insecure || true;
      mc anonymous set none local/file-drive-trash --insecure || true;
      
      echo 'Bucket is ready';
      "