package kakha.kudava.filedrivespring.enums;

public enum ActionType {
    CREATE, UPDATE, DELETE, MOVE,
    UPLOAD, DOWNLOAD, RENAME, COPY,
    MALWARE_UPLOAD, MALWARE_DOWNLOAD,
    MALWARE_SCHEDULED_DELETION, MALWARE_DELETE,
    MOVE_TO_TRASH, RESTORE_FROM_TRASH,
    PERMANENT_DELETE, CLEAR_TRASH, TRASH_AUTO_DELETE

}